### ISSUE TITLE
Pre-cache frame of gif

### ISSUE THREAD

**Issue by Axenntio** [Horus645/swww#15]
I have a gif which has a ~1min duration, and during this time, the CPU fly at 100%.

Is there a way to pre-cache :
- load the GIF, cache it in memory, then display it on the screen
or
- once the first cache is done, save it as a binary file (or something else), for it to be retrieve next time

I'm unsure about possibilities, but this can avoid my CPU to be 100% at my computer start for~1min

**Comment by Horus645** [comment]
That's... very bizarre, actually. Are you using the latest version of `swww` (0.4.0)?

If you don't mind, could you tell me:
  1. Whether you are using two monitors with different resolutions and/or frame rates?
  2. Whether the image you are trying to use needs to be resized in order to be displayed (if so, this is probably the largest factor in your cpu usage, if I had to guess).
  3. How many threads your cpu has?
  
If '2' is true I would recommend trying to resize the gifs using a different tool ([gifsicle](https://github.com/kohler/gifsicle) comes to mind) before sending them to `swww`.

**Comment by Axenntio** [comment]
I'm using the `AUR` package, so i guess it's `0.3.0`. I will try to compile the current version to see if there is any difference.

1. I have only one display, the internal of the laptop (1920x1080)
2. The image is 1500x900 which probably need to be resize to fill screen
3. My CPU has 8 threads (So it takes 1/8 of my CPU)

I will try your solution for 2, just after building `0.4.0`.

---

So same problem for `0.4.0` BUT instead of CPU full for ~1min, it only occur for ~15s.
But the AUR should be updated (or have a `-git` version) I saw that @HakierGrzonzo takes this step for you, maybe if he can update.

Resizing the image also reduce the CPU time to ~10s, on `0.3.0` and `0.4.0`

I thinks it can be a good idea to create a `Troubleshooting` part in the readme to explain why CPU is requested and how to reduce it -> `resize the image`.

Thanks, i guess this solved my issue!

**Comment by Horus645** [comment]
> So same problem for 0.4.0 BUT instead of CPU full for ~1min, it only occur for ~15s.

Alright, this is much closer to what I expected.

> Resizing the image also reduce the CPU time to ~10s, on 0.3.0 and 0.4.0

Yeah, resizing takes a while. `0.4.0` is using the `fast-image-resize` crate, which makes this a lot less painful, but it's still noticeable.

Since you have 8 threads, it really shouldn't be using 100% of your CPU. It should be using only 3 threads - the main one, one for the animation and one for reading the gif. Reading the gif should be most cpu intensive since it also resizes and caches the results. I will check out some stuff before closing this, but it might be that there's simply nothing we can do...


> I thinks it can be a good idea to create a Troubleshooting part in the readme to explain why CPU is requested and how to reduce it -> resize the image

I think this is a great idea! I will keep this open at least until I get around to doing that, as a remainder (I'll probably do it this weekend).

**Comment by HakierGrzonzo** [comment]
I will try to sort out whatever is happening in the AUR package tomorrow, I will have to check why github doesn't send me notifications...

**Comment by HakierGrzonzo** [comment]
I have released `0.4.0` on the AUR, @Horus645 could you tag me when you make a release or send me an email in the future? I don't think github allows notifications on tags.

**Comment by Horus645** [comment]
>  could you tag me when you make a release or send me an email in the future? I don't think github allows notifications on tags.

I thought that might be the problem. Sorry about that. I was only releasing tags because I wasn't 100% confident with the code yet, but I suppose by now I could start doing that...

In any case, I will be sure to tag you for the next tag-only releases in the future!

**Comment by Axenntio** [comment]
> Since you have 8 threads, it really shouldn't be using 100% of your CPU

Juste to makes sure we understand the same things, `top` report me that `swww` use 100% of my CPU, but this is one CPU core.
So i think I just didn't use the right term.
`swww` use 100% of one CPU core.

Thanks for upgrading the AUR package @HakierGrzonzo, maybe I can suggest creating another package `swww-git` which doesn't rely on tag release?
Also, the package also works on `aarch64` so maybe it can be added in the supported architecture?

**Comment by Horus645** [comment]
> swww use 100% of one CPU core.
Aaaah. Alright, well then, that is to be expected.

**Comment by Horus645** [comment]
Added a troubleshooting section to the README, closing.
