### ISSUE TITLE
extremely laggy on hidpi monitor

### ISSUE THREAD

**Issue by Seme4eg** [Horus645/swww#173]
```bash
swww img "$wp" -t=any \
  --transition-duration=2 \
  --transition-step=255 \
  --transition-bezier=0,0,1,1 \
  --transition-fps=30 &
```
Tried to change all parameters above, nothing helped

![rec_01-49-20](https://github.com/Horus645/swww/assets/24554850/f37d88b5-61e7-4ae8-9004-589269415194)

**Comment by flick0** [comment]
transitions seem to be laggy for me too when using fractional scaling

**Comment by flick0** [comment]
swww query for scales:
 - 2
 - 1
 - 1.2
![image](https://github.com/Horus645/swww/assets/77581181/032aceba-4c64-4d5b-b395-f8328138a392)

scale=2
![image](https://github.com/Horus645/swww/assets/77581181/32b32914-92e7-4266-8c63-f878d35aa2af)

scale=1
![image](https://github.com/Horus645/swww/assets/77581181/d115a220-be88-426a-a54e-b498d2039432)

scale=1.2
![image](https://github.com/Horus645/swww/assets/77581181/c1a863da-ff41-47c2-8ced-41bec075a2cf)


why are the values of height and width for scale 1.2 so high?

**Comment by helixoid** [comment]
@flick0 @Horus645 Is the project dead or something ? No commits at all.

**Comment by flick0** [comment]
Wouldn't say the project is dead, horus might be  busy himself and as for me, ive got school and when I get time i *try* to finish some of my old projects that I've left for way too long

**Comment by Seme4eg** [comment]
> transitions seem to be laggy for me when using fractional scaling, are you using fractional scaling too?

Yes i do scale display resolution (scale 4k laptop screen). Using hyprland compositor.

**Comment by Horus645** [comment]
@helixoid, @flick0 sorry, I've been out of town this past week. Generally, I've been pretty busy with college, and I don't think that's going to change anytime soon.

The fundamental problem with most of these issues is that they have a different setup than mine, that I don't know how to test (i.e. multiple monitors, a tablet they are connecting during runtime, a whole different system like nix os, etc.). This means that it's really hard to verify that any changes I've made are correct. Another problem is that I don't know how to automate some of the tests, so I have to manually check if certain things didn't break with my changes. Yet another problem is that many of the issues are related to race conditions, which are just hard in and of themselves in general.

This means that fixing any one issue will likely take me a whole weekend or maybe even more. And right now, I just don't have the energy to work the whole week and then just keep working nonstop on the weekend on these hard-to-solve issues.

If you'd like to fork the repository, I'd be willing to contribute/help you build a new animated wallpaper daemon, but otherwise, I'm afraid you guys are going to have to wait for a while still...

Also, just a sidenote, even if you _do_ fork it, it's not like the problems will go away. These are all pretty annoying stuff.

**Comment by max-niederman** [comment]
I'm also having this issue with no scaling whatsoever.

`swww query`:
```
DP-2: 2560x1440, scale: 1, currently displaying: image: /home/max/Pictures/Wallpapers/cherry.png
DP-3: 2560x1440, scale: 1, currently displaying: image: /home/max/Pictures/Wallpapers/cherry.png
HDMI-A-1: 1920x1080, scale: 1, currently displaying: image: /home/max/Pictures/Wallpapers/cherry.png
```

**Comment by Pytness** [comment]
In my machine, it seems that the method `canvas_change` is taking around 20ms the first frame, and the next ones take ~120ms, ~150ms and ~220ms.

**Comment by Horus645** [comment]
I *think* PR #155 should help with this. You guys might want to try testing it.

**Comment by Seme4eg** [comment]
It did indeed help! Thank you

**Comment by Pytness** [comment]
The merge has indeed helped, it went from ~4 fps to a somewhat smooth animation. 
But I am still getting huge stutters.
