### ISSUE TITLE
Feature Request: Automatically clear cache if initializing from cache fails 

### ISSUE THREAD

**Issue by joshua-holmes** [Horus645/swww#176]
Hello!

**Problem**
I run into an issue when I change monitors where my wallpaper will just be a black screen. When I clear my cache and initialize swww again, it works.

**Solution**
To me, it seems logical to attempt to clear the cache and reinitialize swww automatically if it fails to initialize from cache the first time.

I can implement the solution and push it up myself, I'd just like the go-ahead before I do so. Is this a feature that sounds worth implementing into swww?

Love the simplicity of the program! Thanks!

**Comment by Horus645** [comment]
Mmm. Sorry, I am not sure I understand.

> when I change monitors where my wallpaper will just be a black screen

Do you mean, when you run `swww init`? Does it simply fail? I thought it would print a Warning and succeed.

Or, do you mean that `swww` just crashes when you try to change monitors?

In any case, I am planning to implement a cache-cleaning command and functionality today. So wait for those things first, since they will help you if you want to tackle this.

And yes, contributions - specially bug fixes - are welcome!

**Comment by joshua-holmes** [comment]
Hi, sorry, you're right, my explanation was not very clear. I think I was running into this issue:
1. Run swww with 1 monitor
2. Turn off computer
3. Plug 2nd monitor in
4. Turn on computer
5. swww fails to init and a black screen is shown

However, when I test this now, it seems to work fine. I wonder if you have fixed that since this issue was created. But I do not have issues anymore, so you can close this issue!
