### ISSUE TITLE
Option to show image on recently plugged in monitor

### ISSUE THREAD

**Issue by etrnal70** [Horus645/swww#20]
Hello, thanks for the great app ! Is it possible to add an option to automatically show wallpaper on newly connected monitor ?

**Comment by Horus645** [comment]
Hi! Thanks for the kind words!

Unfortunately, I find this to be outside `swww` scope, because there is no obvious way of doing this. For example, do we simply use the same image that's in the other monitor? What if there are more than one monitor? What if they have different sizes? Do we store state then? Do we make a configuration file?

I am not really interested in supporting any of those options.

Instead, there are tools that were made to handle this exact use case you want. For example, [kanshi](https://sr.ht/~emersion/kanshi/) and [way-displays](https://github.com/alex-courtis/way-displays). You can set them up so that they run `swww img --outputs=<monitor>` when they detect the newly connected monitor.

**Comment by Horus645** [comment]
Hello. This is an old issue, but I would like to point out that #80 will at least set the wallpaper on any monitors you had already previously set with `swww img`. So, you would only have to set them the first time you connect to a new monitor.
