### ISSUE TITLE
Failed to receive answer: io error: Resource temporarily unavailable (os error 11) when plugging or unplugging display

### ISSUE THREAD

**Issue by quexten** [Horus645/swww#26]
I'm running swww version 0.4.3 on Arch, using Sway as the compositor.
Running sway init and then setting an image as the background works, when using my laptop display alone, or using my laptop's display plus an external display that is plugged in.

However, when the swww daemon is running and I plug / unplug the display, the daemon gets into a state where it can not be communicated with.

Setting the background with:
`swww img --transition-speed=1 --transition-step=1 ~/Pictures/my_wallpaper.png`
results in:
`Failed to receive answer: io error: Resource temporarily unavailable (os error 11)`

Running swww kill results in the same error.

I can only get it running again by killing the process, and removing the socket manually.

**Comment by quexten** [comment]
I did a bit more investigation and, after adding a new display, a debug output gets printed:
(main) swww::daemon: New background with output: OutputInfo {...}

The process (in no-daemon mode) seems to be stuck in a syscall.
Specifically, this is the output of strace:
`futex(0x55ba5a44f070, FUTEX_WAIT_BITSET_PRIVATE, 2, NULL, FUTEX_BITSET_MATCH_ANY`

**Comment by Horus645** [comment]
Hello. Thanks for the detailed report!

Really sorry for the time it took me to respond. Unfortunately, I am still really full of stuff for this and next week, so it might take a while until I have a more thorough look at this. I do want to solve it as fast as possible, since it must make using `swww` on a notebook you carry around to plug in other monitors a pain.

**Comment by Matias-Hall** [comment]
I managed to get a stack trace of the daemon before and after unplugging the monitor. It confirms the fact that it hangs at a futex syscall.

[Normal stack trace](https://github.com/Horus645/swww/files/9670264/healty_stack_trace.txt)
[Stack trace after unplugging monitor](https://github.com/Horus645/swww/files/9670265/broken_stack_trace.txt)

**Comment by a-priestley** [comment]
I'm having this issue, but for me it happens when my system idles. Using swayidle, I'm calling for my monitor to go into power-saving mode.
This seems to be in line with what you all are describing with plugging in additional monitors. Only for me, I'm effectively unplugging and plugging the existing monitor back in.

**Comment by quexten** [comment]
I tried the patch and it seems to work very nicely :)

**Comment by Horus645** [comment]
> I tried the patch and it seems to work very nicely :)

Thanks for confirming! I always like to leave things running in my machine for a couple of days before merging, just to make sure nothing explodes.
