### ISSUE TITLE
Saving the last image before the daemon is killed?

### ISSUE THREAD

**Issue by SomeGuyNamedMy** [Horus645/swww#47]
what do you think about this idea, maybe swww could save the location of the last image used after it is killed, and then use that image when the daemon is initialized again?

**Comment by Horus645** [comment]
hm... this would involve us writing that information somewhere. I would rather limit the amount of extra files we use. Furthermore, I feel like this wouldn't be too difficult to implement with a custom script.

I feel like I would rather add another example script showing how one could do something like this instead of implementing it within `swww` itself.

**Comment by SomeGuyNamedMy** [comment]
just realized this issue is stiill open, my bad
