### ISSUE TITLE
Question: step, fps and speed.

### ISSUE THREAD

**Issue by hexive** [Horus645/swww#51]
Hi!

I'm fine tuning an swww integration with [sunpaper](https://github.com/hexive/sunpaper) to allow smooth transitions between time-of-day wallpaper changes. (thank you, btw, this is awesome. I'd previously been using hacky oguri solution for animation that never really worked well)

I'm not sure I fully understand the role of step in the animation process. I'm looking for a sweet spot of longish transition but smooth. Using 3 fps now and 3 step. 

Any assistance is appreciated.

**Comment by Horus645** [comment]
Thanks for the kind words!

So, our algorithm that approaches an image is the most simple you can think of. If we have a pixel that's, for example (in RGB values) `20,20,20`, and we want to go to a pixel that's `40,40,40`, what we do is we add a small value to the original pixel every loop. The `step` determines what this small value is.

So, using 3 `step` for the example above means that, after the first loop we will have `23,23,23`, then `26,26,26`, all the way up to `40,40,40`. 

What `fps` does is determine the loop speed. So, at 3 `fps` you will get one loop every 333ms.

If the goal is a smooth transition, I'd would generally recommend lowering the step as much as possible (so, using 1 for step). That will also mean that the transition will take longer (since you will need more loops to reach the desired pixels). If you want a still longer transition, you can just lower the fps, as you are doing right now.

The longest transition you can obtain would be by setting both fps and step to 1. You can get a smoother transition than you currently have, with the roughly the same duration, with 9 fps and 1 step.

Feel free to ask anything that's still not clear.

**Comment by hexive** [comment]
That makes perfect sense. Thanks again!
