### ISSUE TITLE
Performance issues with bezier in 0.6.0

### ISSUE THREAD

**Issue by JustSimplyKyle** [Horus645/swww#60]
@flick0 since you are the main contributor here
I think nothing illustrates this better than a video. The options used here are:
`--transition-step 1 --transition-type any --transition-duration 5 --transition-fps 255  --transition-bezier=0.85,0,0.15,1`

[0.6.0_v2.webm](https://user-images.githubusercontent.com/68589851/206733372-475f6445-fbe8-40c1-8bce-21aa29d01e7c.webm)

Even using "no beziers" it is still pretty slow.(`--transition-bezier=0,0,1,1`)

[no_bezier.webm](https://user-images.githubusercontent.com/68589851/206726564-034cd0e4-764e-4f2c-be13-4f8ca07ec3ce.webm)

I know that bezier is a bit performance heavy, but compared to the last release(0.5.0), it's noticeably faster than both of the above
Options used here are: `--transition-speed 20 --transition-type any --transition-fps 255`

[0.5.0.webm](https://user-images.githubusercontent.com/68589851/206725575-fae5b7e4-3e46-4f10-95bc-af9b9a12297a.webm)

**Comment by flick0** [comment]
Try using a higher transition step

**Comment by JustSimplyKyle** [comment]
Yeah, something like 90 seems to be much smoother
I still don't understand what does step mean tho...
> Larger values will make the transition faster, but more abrupt.

The documentation seems to imply that lower values have smoother playback, but it doesn't seem to be the case here

> A value of 255 will always switch to the new image immediately.

This somehow only applys to simple? `any`(the one I'm using) won't switch to the image immediately

**Comment by flick0** [comment]
Transition step is basically the speed at which a pixel changes from one color to another

smaller step value is "smoother" in the sense the edges of transition are faded and smooth, whereas on larger step values there is a noticeable harder line

**Comment by Horus645** [comment]
I see there's some misunderstand over what `step` does (you are the second one to say they don't get it). 

The way one image transition into the next in `swww` is by approximating the individual pixels. If there are two pixels:

`0,0,0`
`10,10,10`

With a step of '1', we will add '1' to `0,0,0` every frame. So after one frame it will be `1,1,1`, after another frame `2,2,2`, and so on. A step of '10', in this case, would go to `10,10,10` immediately. Since a color can only have values in the range `0-255`, a step of 255 guarantees we will reach the next color in just one frame.


Now, the transitions other than `simple` depend also on an imaginary line that's going across the screen. In the case of `outer`, that line is a circle that shrinks. For `grow`, it is a circle that expands. That line determines what pixels change and what don't. That is how we can achieve our animations.

If I understand correctly, you would like for the transition to be faster/more similar to version 0.5.0. You should then try higher `transition-step` and lower `transition-duration`. The `transition-bezier` option won't make the transition faster.

**Comment by Horus645** [comment]
As an aside, I would like to point out this isn't really a performance problem. `swww` is behaving as intended. It is taking so long most likely not because calculating bezier is slow, but rather because you are calling with `transition-duration 5`, which will make it always take roughly 5 seconds to complete its animation.

Try something like `--transition-duration 1 --transition-step 150`. If it is *still* slow, then we might a performance problem.

**Comment by JustSimplyKyle** [comment]
Yeah, *stepping* up transition-step seems to fix it.
The performance issues that I'm mentioning is not that the speed itself is too long
But instead, the merging of the pixels feel laggy, like I can see the individual "chunks"

**Comment by JustSimplyKyle** [comment]
Yeah, I'm pretty much done.
Although... Maybe some more documentation can be added(man pages for example), explaining each option with more details than in the current help
