### ISSUE TITLE
daemon unsets on screen shutdown

### ISSUE THREAD

**Issue by DMNinja** [Horus645/swww#65]
I'm Not sure if it's intended behavior, so i'll refrain from assigning a label.

Upon physically powering off a screen, swww doesn't kill the daemon but unsets itself. On screen powerup i need to manually use the swww img command to set the image again. 

Is it possible to store the loaded image and when swww detects a screen powering on (and thus swww query returns the screen data) to autoload what was previously on that screen?

**Comment by Horus645** [comment]
For this use case in particular, I would recommend using something like [kanshi](https://sr.ht/~emersion/kanshi/). It is a tool specifically made to deal with setup when powering on and off / connecting and disconnecting stuff.

You would have to come up with a series of scripts to achieve this kind of functionality. For example, you could wrap `swww img` in a script that saves the absolute path of the current image being displayed, and then on power on you configure kanshi to call `swww img` with the image you saved.

Someone else suggested something similar to this before ([#47](https://github.com/Horus645/swww/issues/47)). I proposed instead to offer examples of the scripts that could achieve this.

In the end, I didn't get around doing that. I guess this issue is a good reminder.

**Comment by DMNinja** [comment]
I wrote a simple script, but it's not a fully-fledged solution

```profile {
    output HDMI-A-1 disable
    CBG =$(swww query | grep -oP '"\K[^"\047]+(?=["\047])')

profile{
    output HDMI-A-1 enable
    exec 'swww img ~/.wallpapers/$CBG'
    }```

This is supposed to write the current background to a variable, and pass it to a swww exec command upon screen powerup, but it's incomplete. At least the regex is fully consistent in grepping the current file used as a background

**Comment by Horus645** [comment]
Multiple people have asked this of me, so I am thinking of just storing something at `$XDG_CACHE_DIR/swww_last_image` or something. It would be pretty basic though.
