### ISSUE TITLE
Error spawning swww-daemon: no such file or directory

### ISSUE THREAD

**Issue by fedoranvar** [Horus645/swww#70]
good day to you!

on some commit after `27b048d80d414f6c903fc496527a79d49a247a4e`

there is an error after launching  `swww init`
![image](https://user-images.githubusercontent.com/52028706/209061706-d89acde7-d906-41bb-906b-fda45dd08531.png)
 
 
 and output from tests:
 
![image](https://user-images.githubusercontent.com/52028706/209064506-0c50fff1-2821-457c-876e-6d90691c914f.png)

**Comment by Horus645** [comment]
I assume you are building from master. We have two binaries now: `swww` and `swww-daemon`. Both must be in your `$PATH` for the program to work. You are going to have to update your installation / packaging method so that it installs both programs.

This is the main reason I haven't released a new version yet. I am waiting a bit because it *will* break all packages.

**Comment by fedoranvar** [comment]
yes, problem resolved.

thank you!
