### ISSUE TITLE
FR: Supply a cache file instead of GIF?

### ISSUE THREAD

**Issue by max-ishere** [Horus645/swww#97]
I have a nice animation on boot that transitions to a static image. In #93 I have figured out that you can
```
swww img i.gif
swww kill
swww init
```
and the loading time in `init` is basically 0. So is there a reason we cant have a command that makes the daemon perform those really fast steps that happen in init, but for loading the GIF while it is already running?

**Comment by Horus645** [comment]
I don't get what you are saying. The three commands are not 0. Only the final `init` is 0 because the time was transferred to your first command `swww img i.gif`. If we moved all three commands into the daemon, they would take the exact same amount of time as the whole thing.

**Comment by Horus645** [comment]
As for why we don't cache everything, it is because we would have to come up with an efficient way of storing those things. And the big problem is that decoders for specific formats (like GIF), use up a lot of memory. This increases the daemon overall memory usage, which is something I want to avoid, because it is a long-running program. I managed to cut memory usage by half when I moved the decoding image part out of the daemon and into the client.

So, we currently only cache the image by its raw bytes (technically, we use `bincode`, so it's probably a little more complex than that), which makes it very easy to "decode" (just read the file). This ensures we won't be wasting RAM, but the price is that files are pretty big. If we were to cache every file every used by the user, it would quickly grow quite a lot.

> I have a nice animation on boot that transitions to a static image.

This... is really not the use case I had envisioned for `swww`. But, nevertheless, here's what you can do:

```
swww img i.gif # send in the gif you want
cp ~/.cache/swww/* ~/Pictures/BootAnimations/ # store the cached gifs somewhere


# On booting:
cp ~/Pictures/BootAnimations/ ~/.cache/swww # restore the cached gifs
swww init # init the daemon with the cached gifs
swww img /path/to/img # send in your image with the desired transition
```

I feel you already figured this out though.

**Comment by Horus645** [comment]
Ah, I think I understand what  you mean now. I could maybe implement a `--cache` options that allows you to supply a custom cache location. This might make things easier for you:

```bash
swww img i.gif --cache ~/Pictures/BootAnimations # send in the gif you want , at the specified cache location

# On booting:
swww init --cache ~/Pictures/BootAnimations # init the daemon with the cached gifs
```

**Comment by max-ishere** [comment]
I dont think you need i.gif with --cache. Because the point was to have this interface:
```
swww from-cache cached/*
```
And it will skip the processing and just straight to loading the file. Maybe have a `--fallback i.gif`

**Comment by max-ishere** [comment]
But... Now that I think about it it probably doesn't make sense to trade sad space for CPU load. The only time you need a snappy load is when you log in to wm. And that can already be done by replacing files ahead of time.

**Comment by max-ishere** [comment]
And if you are already displaying something and call `img i.gif` you won't see it until it's ready.

**Comment by max-ishere** [comment]
I think I opened the issue impulsively and I don't think the feature is any useful. I think we can close this for now. Maybe implement this later if needed..?

**Comment by Horus645** [comment]
I also realized implementing this would actually be a lot more annoying than I had initially predicted. If you think it isn't that useful, I'd rather not go through with it.
